---
title: "Answers to exercises in Efficient Performance"
author: "Colin Gillespie and Robin Lovelace"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chapter 7 solutions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{Chapter 2 solutions}
-->

## Chapter 7 Solutions


### Profvis Monopoly


```{r eval=FALSE}
## Original function
profvis({
  for(i in 1:10000) {
    current = 0
    df = data.frame(d1 = sample(1:6, 3, replace=TRUE), 
                    d2 = sample(1:6, 3, replace=TRUE))
    
    df$Total = apply(df, 1, sum)
    df$IsDouble = df$d1 == df$d2
    
    if(df$IsDouble[1] & df$IsDouble[2] & df$IsDouble[3]) {
      current = 11#Go To Jail
    } else if(df$IsDouble[1] & df$IsDouble[2]) {
      current = current + sum(df$Total[1:3])
    } else if(df$IsDouble[1]) {
      current = current + sum(df$Total[1:2])
    } else {
      current = current + df$Total[1]
    }
  }
}, interval = 0.005)
```

```{r eval=FALSE}
## With improvements
profvis({
  for(i in 1:10000) {
    current  =0 
    dd = matrix(sample(1:6, 6, replace=TRUE), ncol=2)
    Total = rowSums(dd)			
    IsDouble = dd[,1] == dd[,2]
    if(IsDouble[1] && IsDouble[2] && IsDouble[3]) {
      current = 11#Go To Jail
    } else if(IsDouble[1] && IsDouble[2]) {
      current = current + sum(Total[1:3])
    } else if(IsDouble[1]) {
      current = current + Total[1:2]
    } else {
      current = Total[1]
    }
    current
  }
  
}, interval = 0.005)
```
```{r eval=FALSE}
## Abandoning the vectorised approach
profvis({
  for(i in 1:10000) {
    die1 = sample(1:6, 2, replace=TRUE)
    current = sum(die1)
    if(die1[1] == die1[2]) {
      die2 = sample(1:6, 2, replace=TRUE)
      current = current + sum(die2)
      if(die2[1] == die2[2]){
        die3 = sample(1:6, 2, replace=TRUE)
        if(die3[1] == die3[2]){
          current = 11
        } else {
          current = current  + sum(die3)
        } 
      } 
    }
  }
}, interval = 0.005)
```
